breadtubetv/breadtubetv

LICENSE

I think we should be licensing this with GNU GPLv3. 
I have followed the instructions https://choosealicense.com/licenses/gpl-3.0/ to install the license.
Could I get a sanity check that everything is correct in here, notably around line 13.

GNU GPL v3 License

---

config.toml
layouts/_default/baseof.html
layouts/partials/base/head.html
layouts/partials/base/sidebar.html
layouts/partials/channels/card.html
layouts/partials/channels/row.html
layouts/partials/videos/card.html
static/css/site.css

Also includes some accessibility improvements

Channel Image on Video Card

---

content/_index.md
data/channels.yml

Homepage is "breadtube" tagged channels

Tag BreadTue

---

layouts/partials/videos/card.html

Enable Full Screen mode on the video iFrame

iFrame allowfullscreen

---

static/css/site.css

no max width on channels

---

config.toml
content/_redirects

allows simply sharing
https://deploy-preview-57--breadtubetv.netlify.com/reddit 
https://deploy-preview-57--breadtubetv.netlify.com/discord
https://deploy-preview-57--breadtubetv.netlify.com/twitter 
https://deploy-preview-57--breadtubetv.netlify.com/facebook
https://deploy-preview-57--breadtubetv.netlify.com/tumblr
https://deploy-preview-57--breadtubetv.netlify.com/github
https://deploy-preview-57--breadtubetv.netlify.com/youtube
or in production
https://breadtube.tv/reddit
https://breadtube.tv/discord
https://breadtube.tv/twitter
https://breadtube.tv/facebook
https://breadtube.tv/tumblr
https://breadtube.tv/github
https://breadtube.tv/youtube

Redirects for Social

---

static/css/site.css

Channel Card Needs Max Width

---

data/channels/hbomberguy.yml
data/channels/philosophytube.yml
data/channels/ploppy111.yml

Fixed spelling on Hbomberguy and Philosophy Tube. Also removed duplicate for Kevin Logan.
Preview: https://deploy-preview-78--breadtubetv.netlify.com/

Spelling Fixes

---

data/channels/theserfs.yml

Suggested on Website
⚠️  subscriber count was wrong due to in-development subscriber count
https://deploy-preview-75--breadtubetv.netlify.com/

The Serfs Subscriber Update

---

layouts/partials/channels/card.html

Quick fix for linking to channels, will help when I'm adding content for linking the submitter.
We need to do much more with channels, would love others input on what that looks like.
https://deploy-preview-77--breadtubetv.netlify.com/#contrapoints
https://deploy-preview-77--breadtubetv.netlify.com/#petercoffin
https://deploy-preview-77--breadtubetv.netlify.com/#thejuicemedia

Channel in Path

---

config.toml

https://deploy-preview-84--breadtubetv.netlify.com/

Typo Against

---

content/playlists/authority.md
data/videos.yml

https://deploy-preview-91--breadtubetv.netlify.com/playlists/authority/

Stimulator / Trouble 18 : ACAB

---

content/_redirects

https://www.youtube.com/channel/UCv8O1dx5UjWHlJuo_Wl6o5w
In the spirit of using the Master's tools to bring down the house I've put together a YouTube channel for BreadTube.
So far I have added some playlists which already exist on the website.
This gives people a much more YouTube friendly experience for watching a playlist, this is especially important now during our projects early stages. 
We will continue to build out content on the website, this addition of a channel just gives us another way to distribute, and will also be something we can leverage as we expand the capabilities of the `bake` script which downloads information off YouTube.
With the addition of this it also solidifies the use of the BreadTube content Google Account, something which is running under a Google …

Link to YouTube Channel

---

data/channels/democracyatwork.yml
data/channels/democracynow.yml
data/channels/empirefiles.yml
data/channels/friendlyjordies.yml
data/channels/internetcommentiquette.yml
data/channels/seculartalk.yml
data/channels/thejuicemedia.yml
data/channels/themajorityreport.yml
data/channels/theyoungturks.yml
data/channels/wisecrack.yml

Starting to think about more explicit tagging, leaving breadtube for things on homepage (that tag can be changed later)

Being more specific with tags, making homepage more breadtubey

---

data/channels/threearrows.yml

https://deploy-preview-110--breadtubetv.netlify.com/#threearrows

Fixed three arrows count

---

config.toml

Just sets an order so that we can reliably position them, happy to update the actual order.

Footer Link Order

---

layouts/partials/base/banner.html
static/css/breadtube.css

Add link to Home in the Banner title
Removed some unnecessary css

Banner Link to Home

---

content/channels/new.md
content/playlists/new/index.md
layouts/_default/baseof.html
layouts/partials/base/banner.html
layouts/partials/base/navigation.html
layouts/playlists/list.html
static/css/breadtube.css

Update Search, Navigation, and Add UX

---

static/css/breadtube.css

Fixes horizontal alignment of page lists (see Search alignment and list alignment on current pages).

Fix margins on lists

---

content/playlists/anarchist-revolution-syria.md
content/playlists/authority.md
content/playlists/earth-strike.md
content/playlists/organizing.md
content/playlists/welcome.md

Just shows that the playlists are what they are by highlighting the menu item.

Playlists Menu Highlighting

---

data/channels/theserfs.yml

Reverts breadtubetv/breadtubetv#145

Revert "The Serfs New Channel"

---

layouts/partials/channels/new.html
layouts/partials/playlists/new.html
static/css/breadtube.css

Noticed people adding a description in the video urls textarea
https://deploy-preview-167--breadtubetv.netlify.com/channels/new
https://deploy-preview-167--breadtubetv.netlify.com/playlists/new/

Playlist and Channel Description

---

layouts/partials/base/head.html
layouts/partials/search/code.html

Drastically improves page load time, discovered in #165 
improved https://deploy-preview-169--breadtubetv.netlify.com/#search:dirk%20kelly
current https://breadtube.tv/#search:dirk%20kelly

Allows searching immediately, instead of after image load

---

content/privacy.md
content/privacy/_index.md
layouts/_default/baseof.html
layouts/partials/base/create.html
layouts/partials/base/footer.html
layouts/partials/search/bar.html
layouts/privacy/list.html
static/css/breadtube.css

https://deploy-preview-157--breadtubetv.netlify.com/privacy/

Privacy Policy

---

bake/cmd/update.go

#FirstGoCommit let me know if there are optimizations for this.

Use Config for Bake Update

---

layouts/partials/search/code.html

Fixes the search clear functionality for #184

Allow search to be cleared

---

bake/providers/youtube.go

Part of #171. Automatically downloads and saves the channel thumbnail when importing the channel. There will be merge conflicts with #185 depending on which is merged first.
Interim solution until the refactor (#183) is complete.

Bake CLI - Download Channel Thumbnail

---

data/videos/askamortician/F4zRwIWagKs.yml

https://deploy-preview-238--breadtubetv.netlify.com/askamortician/

askamortician title fix

---

content/noncompete.md
content/playlists/how-anarchism-works.md
data/videos/noncompete/Hmy1jjRnl8I.yml
data/videos/noncompete/TKoiAXX6KFs.yml
data/videos/noncompete/TquMOei4C4o.yml
data/videos/noncompete/ZzEl5RIMp7M.yml

https://deploy-preview-231--breadtubetv.netlify.com/playlists/how-anarchism-works/

Non Compete - How Anarchism Works

---

content/seculartalk.md
data/channels/seculartalk.yml
data/videos/seculartalk/2UbDdd6WJLc.yml
data/videos/seculartalk/8fkFAmIxgcs.yml
data/videos/seculartalk/RehaBr5XtkE.yml
data/videos/seculartalk/vbl7TnYt0Lw.yml

https://deploy-preview-240--breadtubetv.netlify.com/seculartalk/

Secular Talk Content

---

data/channels/drlayman.yml

Fixed an issue with Dr Layman.

Bufgix: Fix some issue with the Dr Layman content

---

content/fleamarketsocialist.md
data/channels/fleamarketsocialist.yml
data/videos/fleamarketsocialist/3V_ONBEtYHk.yml
data/videos/fleamarketsocialist/5eMJJgTL0Tc.yml
data/videos/fleamarketsocialist/z9rSIT_3_JM.yml

https://deploy-preview-260--breadtubetv.netlify.com/fleamarketsocialist/

Flea Market Socialist Videos

---

content/deadheadanimation.md
content/faradayspeaks.md
content/noncompete.md
content/playlists/deprogramming.md
content/shaun.md
content/threearrows.md
data/videos/faradayspeaks/nX9MZ593MTU.yml
data/videos/noncompete/aqRCSzUTGcM.yml
data/videos/noncompete/yL3FTFLQEEw.yml
data/videos/shaun/VUbxVfSqtt8.yml
data/videos/threearrows/69obN625Fjs.yml

Adds a playlist and lists some additional videos on their relevant creators page.
https://deploy-preview-262--breadtubetv.netlify.com/playlists/deprogramming/
Playlist Changes
https://github.com/breadtubetv/breadtubetv/pull/262/files#diff-45f0e4f814079630802c629dbacb034f

Deprogramming

---

content/andrejpskraba.md
content/channels/_index.md
content/muke.md
data/videos/andrejpskraba/78BFFq_8XvM.yml
data/videos/muke/WGRC5AA1wF0.yml

Remove dead videos

---

layouts/channel/single.html
static/css/breadtube.css

Show a channel's tags
https://deploy-preview-264--breadtubetv.netlify.com/angiespeaks/
https://deploy-preview-264--breadtubetv.netlify.com/contrapoints/

Show tags (not breadtube) on channels

---

content/seculartalk.md
data/channels/seculartalk.yml
data/videos/seculartalk/-H6aFWphNcA.yml
data/videos/seculartalk/3XUzKlhDZDM.yml
data/videos/seculartalk/Xi7jbtioxCE.yml
data/videos/seculartalk/yBObh_XC1A4.yml

https://deploy-preview-278--breadtubetv.netlify.com/seculartalk

Secular Talk

---

content/_index.md
content/contrapoints.md
data/videos/contrapoints/n9mspMJTNEY.yml

https://deploy-preview-281--breadtubetv.netlify.com/contrapoints/
https://deploy-preview-281--breadtubetv.netlify.com/videos/#search:beauty

Beauty | Contrapoints

---

layouts/partials/channels/row.html

https://deploy-preview-290--breadtubetv.netlify.com/channels/#search:

Magic Sort Order

---

layouts/channel/single.html
layouts/partials/channels/edit.html
layouts/partials/search/code.html

Adds a form to each channel to support users suggesting updates.
https://deploy-preview-291--breadtubetv.netlify.com/beauofthefifthcolumn/#update

Channel Update Form

---

content/channel/zeria.md
data/channels/zeria.yml
data/videos/zeria/PaMJGf8UXJM.yml
data/videos/zeria/RB3JQhghbrs.yml
data/videos/zeria/en4bcnxpNO0.yml
data/videos/zeria/iGYnmZ9uN7g.yml

https://deploy-preview-273--breadtubetv.netlify.com/zeria

Zeria content update

---

content/channel/vaush.md
data/channels/vaush.yml
data/videos/vaush/-94STO1-D5Q.yml
data/videos/vaush/4CZUNd-N1ko.yml
data/videos/vaush/BHQapW0HzEw.yml
data/videos/vaush/JlJkVPn2NRM.yml

https://deploy-preview-274--breadtubetv.netlify.com/vaush/

Vaush content update

---

content/channel/justwondering.md
data/channels/justwondering.yml
data/videos/justwondering/F1tEzTOHPDY.yml

https://deploy-preview-304--breadtubetv.netlify.com/justwondering/

Just Wondering Update

---

content/channel/dirkkelly.md
data/channels/dirkkelly.yml
data/videos/dirkkelly/-NCCYXrZBho.yml
data/videos/dirkkelly/9gvkwp4uPc0.yml
data/videos/dirkkelly/U9Oao0NOs7s.yml
data/videos/dirkkelly/wqpTO6rrajk.yml

https://deploy-preview-303--breadtubetv.netlify.com/dirkkelly/

dirkkelly update

---

content/_redirects

https://deploy-preview-308--breadtubetv.netlify.com/github/issues/new

Fix github redirect

---

netlify.toml

Hugo 0.57.2

---

scripts/migrate/01_creator_pages.sh
scripts/migrate/02_video_pages.sh

update migrate scripts to allow a fresh import and replace of a channel and its videos

migrate script fixes

---

layouts/channel/list.html
layouts/partials/channels/edit.html

Channel edit form uses the children videos for the video edit list

include videos in the channel edit

---

content/channels/bigbreadbrainz/_index.md
content/channels/bigbreadbrainz/videos/EonmLFFic5E.md
content/channels/bigbreadbrainz/videos/NKmn8A3Zv44.md
content/channels/bigbreadbrainz/videos/QQwJZ2fgTCU.md
content/channels/bigbreadbrainz/videos/gNKwTWKOdA8.md
content/channels/bigbreadbrainz/videos/lm6xs0gur6U.md
content/channels/bigbreadbrainz/videos/nA34Gkucr_E.md
content/channels/bigbreadbrainz/videos/o4yNObH25oU.md

https://deploy-preview-372--breadtubetv.netlify.com/bigbreadbrainz/

BigBreadBrainz Update
