breadtubetv/breadtubetv

config.toml, content/_index.md, data/links.yml, layouts/partials/tile_slate.html
https://deploy-preview-3--breadtubetv.netlify.com/
This just cuts down on the amount of home page items for a bit while we try to figure out what is we show, really keeping it to the BreadTube community.
It also adds a configuration which would mean we could create sub category pages, this feature could also become more javascript based in the future.
A good piece of research would be pulling all the channels that have been linked in https://reddit.com/r/breadtube.
=> Filter Home Page on Tag "Socialism"

data/channels/anactualjoke.yml, data/channels/anarchopac.yml, layouts/partials/channels/card.html
Adds support for the upgrade path of providers with additional `providers` information, include YouTube and Patreon (this will be a huge support for people, doesn't need an API atm).
This is meant to be safe to merge as is, providing an upgrade path which could likely be solved by the [`bake channel import` yaml formatting PR#54](https://github.com/breadtubetv/breadtubetv/pull/54).
=> Providers Data Structure. Patreon & YouTube

static/css/breadtube.css
Flushed up against side
Fixed (not flushed)
Used a bad example because of the title wrap
=> list item padding on mobile

bake/cmd/update.go, bake/util/channel.go, bake/util/channel_test.go
This just makes sure that nil values in YAML don't cause panics.
Includes tests!
=> Handle nil values, missing URLs

static/site.webmanifest
This improves the Progressive Web App experience by
- Setting an application name
- Displaying as a browser
- Users can share urls
- Users can go back and forth
(url will say https://breadtube.tv/)
=> Manifest Update

layouts/partials/channels/row.html
Uses the slug attribute which is downcase to sort, instead of name.
Fixes a serious issues where channels were listed based on case sensitivity, meaning that channels starting with a lower case "a" were after those with an upper case "Z"
=> Sort Channels By Slug

README.md, bake/cmd/import.go, bake/cmd/root.go, bake/providers/youtube.go
This PR addresses one aspect of #171 - it allows the user to set the path of the channels dir, rather than having to be within the `$repo/bake` directory.
=> Allow config of channels dir

bake/cmd/import.go, bake/providers/youtube.go, bake/util/channel.go, bake/util/vidoes.go
Part of #171. This is an interim improvement to the `bake` CLI while on-going work is being completed to refactor it. This PR adds a feature to the `import` command so that when a channel is imported, the channel page (in the form of breadtube.tv/channelSlug) is created automatically. 
Additionally, the `permalink` value has been added to the `channelSlug.yml` definition.
=> Bake CLI - Create Channel Pages

layouts/partials/videos/card.html
https://deploy-preview-225--breadtubetv.netlify.com/contrapoints/
Video cards are missing a link due to #212
=> Bug Fix: Missing Video Link

static/css/breadtube.css
https://deploy-preview-227--breadtubetv.netlify.com/
Moved the flex component to the video link container.
The previous refactor allows us to link to the video and the title, but the addition of another object broke the flex model.
Small UI issue in that a short description puts unnecessary whitespace before the channel (first video vs the rest)
=> fixed responsive video card

layouts/partials/channels/new.html, layouts/partials/playlists/new.html
Content suggestions are going to hit Discord directly, no need to have email anymore, in fact it's a security floor.
Todo in a further PR
- Thank you page
- Linking to discord
- Linking to Github
- Showing video of how to add yourself
=> remove email from forms

config.toml, content/videos/_index.md, layouts/partials/base/footer.html, layouts/videos/list.html
Shows the videos on their own page, makes the navigation completely content related. Gives us the pages necessary to add video search and suggest features in the future.
https://deploy-preview-241--breadtubetv.netlify.com/videos/
Sort order is based on channel name presently, if we were able to get the video created dates through the bake command we could sort most recent first.
=> Videos Navigation

.github/settings.yml
Set GitHub configuration from the settings file, allows for democratic decision making around vital configuration.
Once we have this in I would like to discuss whether we can [allow admins to merge without a review](https://github.com/breadtubetv/breadtubetv/compare/github-settings?expand=1#diff-f4a8cbb8ecd8c5ca594e8e75183845e1R90) related to #147.
Current state of the project is very dependent on manual work of developers, including in the pull request process.
- There are now notifications in Discord of submissions and pull requests
- There is a pull request #200 to update content that is now 9 days old
- Videos are being included in submission which gives context
- There is now a link to r/BreadTube #247 search results for each submission
We still need to complete documentation, but …
=> Github Settings

layouts/channel/single.html
Via Discord
```
asdfjasdjkflToday at 7:24 PM
hey folks. Usually when I look up a channel on /r/breadtube I search for
title:channel+name OR flair:channel+name
because when the channel name isn't in the title it's usually in the flair
I was wondering if y'all want to change the r/breadtube link on channel pages to something like that
```
=> reddit link uses title:name OR flair:name

data/videos/meanstv/8uaInDOjYyw.yml, layouts/_default/baseof.html, layouts/channels/list.html, layouts/partials/base/navigation.html, layouts/partials/playlists/row.html, layouts/partials/search/bar.html, layouts/partials/search/code.html, layouts/partials/videos/card.html
Adds Search to the top of every page, works across video, channel, and playlist content.
=> Global search

layouts/partials/search/code.html
Fixes the url getting every letter of the search
- Visit https://breadtube.tv/channels
- Search for `contrapo`
- Click `back`
- You should be on https://breadtube.tv/channels/#search:contrap
- click `Contrapoints`
- Click `back`
- You should be on https://breadtube.tv/channels/#search:contrap
- Click `back`
- You should be on https://breadtube.tv/channels/#search:contra
- Visit https://deploy-preview-279--breadtubetv.netlify.com/channels
- Search for `contrapo`
- You should be on `null`
- Click `forward`
- You should be on https://deploy-preview-279--breadtubetv.netlify.com/channels
- Search for `contrapo`
- Click `Contrapoints`
- Click `back`
- You should be on https://deploy-preview-279--breadtubetv.netlify.com/channels/#search:contrap
- Click `back`
- You should be on `null`
=> fix url changing

content/privacy/_index.md
Minor fix. But what’s actually up with the https://github.com/breadtube org, was it just a typo and always owned by someone else?
=> Fix GitHub organization link in Privacy Policy

layouts/partials/channels/edit.html, layouts/partials/channels/new.html
https://deploy-preview-293--breadtubetv.netlify.com/contrapoints/
Adds better formatting to Channel Update, and a comment field to add and edit.
=> Channel Submission Comments

.github/settings.yml
Currently all changes to the website require a review from at least one other person before being deployed. The change to this policy has been an open discussion since the #147 where a merge was forced through in order to support The Serfs during their time of being censored by Google.
Now that we have fully working scripts for downloading content I think we should move into a phase of rapid content changes to the site to allow for usage of the website in distribution, eg: tweeting a link to a breadtube channel page. This sort of functionality will be useful for a proof to concept to the community of the potentials for a website using this open source platform to monitor content in an "automated" way.
This is a request for change to permissions to allow admin merging without a review from …
=> Permissions Change: Admins Merge on data and content

layouts/partials/videos/card.html
Shortens all video cards and removes the need to manually edit the description.
This is a quick hack, would like a more comprehensive solution. It's also embedded in a few of the recent content updates, but wanted to call it out in this PR.
=> Short Video Cards
